### ISSUE TITLE
Spacing vowel signs block mark attachment

### ISSUE THREAD

**Issue by dscorbett** [notofonts/limbu#6]
### Font
NotoSansLimbu-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/limbu/releases/tag/NotoSansLimbu-v2.005
Date: 2024-06-09

### Font version
Version 2.005

### Issue
The spacing vowel signs U+1923..U+1926 block mark attachment. Compare the spacing medial consonants U+1929 and U+192B, which do not block mark attachment.

### Character data
ᤁᤣ᤺ᤲᤁᤤ᤺ᤲᤁᤥ᤺ᤲᤁᤦ᤺ᤲ
U+1901 LIMBU LETTER KA
U+1923 LIMBU VOWEL SIGN EE
U+193A LIMBU SIGN KEMPHRENG
U+1932 LIMBU SMALL LETTER ANUSVARA
U+1901 LIMBU LETTER KA
U+1924 LIMBU VOWEL SIGN AI
U+193A LIMBU SIGN KEMPHRENG
U+1932 LIMBU SMALL LETTER ANUSVARA
U+1901 LIMBU LETTER KA
U+1925 LIMBU VOWEL SIGN OO
U+193A LIMBU SIGN KEMPHRENG
U+1932 LIMBU SMALL LETTER ANUSVARA
U+1901 LIMBU LETTER KA
U+1926 LIMBU VOWEL SIGN AU
U+193A LIMBU SIGN KEMPHRENG
U+1932 LIMBU SMALL LETTER ANUSVARA

### Screenshot
![ᤁᤣ᤺ᤲᤁᤤ᤺ᤲᤁᤥ᤺ᤲᤁᤦ᤺ᤲ](https://github.com/notofonts/limbu/assets/1124347/572d3e5c-6db7-4201-94bd-0678b68ed106)

**Comment by simoncozens** [comment]
Fixing this causes another issue:
![shape](https://github.com/user-attachments/assets/5fe9021f-ea5c-4944-9a0f-7193f08d9bb7)

Perhaps it would be easier just to decompose -oo and -au as other Indic fonts do.

**Comment by simoncozens** [comment]
Yeah, that's the ticket.
![shape](https://github.com/user-attachments/assets/81295773-8d72-4b64-aeeb-50c75dbb6850)
